"use client";

import { ArrowLeft, BookOpenCheck, BriefcaseBusiness, Check, ClipboardCheck, FileText, GraduationCap, MapPin, ShieldCheck, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { courses } from "@/data/opportunities";
import type { AppLanguage, CandidateProfile, OpportunityMatch } from "@/lib/product-types";
import { SourceCitation } from "@/components/bhasha/shared";

export function CounsellorScreen({ language, profile, matches, onBack, onResume }: { language: AppLanguage; profile: CandidateProfile; matches: OpportunityMatch[]; onBack: () => void; onResume: () => void }) {
  const hi = language === "hi";
  const eligible = matches.filter((item) => item.eligible).slice(0, 4);
  const near = matches.filter((item) => !item.eligible).slice(0, 2);
  const relevantCourses = courses.filter((course) => course.relatedTrades.includes(profile.trade ?? "")).slice(0, 2);
  return (
    <div className="mx-auto w-full max-w-[1320px] px-4 pb-28 pt-7 sm:px-7 lg:px-12 lg:pt-9">
      <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><button onClick={onBack} className="mb-4 inline-flex min-h-10 items-center gap-2 rounded-xl pr-3 text-sm font-extrabold text-[#557067] hover:bg-[#e9f1ea]"><ArrowLeft className="size-4" />{hi ? "उम्मीदवार view" : "Candidate view"}</button><p className="text-xs font-black uppercase tracking-[.11em] text-[#5c8173]">{hi ? "केवल इस session का सार" : "Current session only"}</p><h1 className="mt-1 font-[family-name:var(--font-display)] text-4xl font-bold tracking-[-.04em] sm:text-5xl">{hi ? "काउंसलर सारांश" : "Counsellor summary"}</h1><p className="mt-3 text-[15px] leading-7 text-[#687a72]">{hi ? "उम्मीदवार की जानकारी, पात्रता, gaps और अगले कदम एक नज़र में। कोई permanent record नहीं बनाया गया।" : "Candidate details, eligibility, gaps and next steps at a glance. No permanent record has been created."}</p></div><Button onClick={onResume} variant="outline" className="min-h-11 rounded-xl border-[#cad8cd] bg-white font-black text-[#294b41]"><FileText />{hi ? "रिज़्यूमे देखें" : "View resume"}</Button></div>

      <section className="mb-5 overflow-hidden rounded-[28px] border border-[#d8e2d9] bg-white shadow-[0_18px_60px_#203e340b]"><div className="grid gap-6 bg-[#173f34] p-6 text-white sm:grid-cols-[auto_1fr_auto] sm:items-center sm:p-8"><span className="grid size-20 place-items-center rounded-[24px] bg-[#dff0a7] text-2xl font-black text-[#305223]">{profile.initials}</span><div><p className="text-xs font-black uppercase tracking-[.1em] text-white/55">Candidate</p><h2 className="mt-1 font-[family-name:var(--font-display)] text-3xl font-bold">{profile.name}</h2><p className="mt-2 flex items-center gap-2 text-sm text-white/70"><MapPin className="size-4" />{profile.location}</p></div><div className="rounded-2xl bg-white/10 p-4"><span className="flex items-center gap-2 text-sm font-black"><ShieldCheck className="size-5 text-[#dff0a7]" />Profile reviewed</span><p className="mt-1 text-xs text-white/60">Demo session · not saved</p></div></div><div className="grid gap-px bg-[#dde5de] sm:grid-cols-4">{[{ icon: GraduationCap, label: hi ? "शिक्षा" : "Education", value: profile.education }, { icon: ClipboardCheck, label: hi ? "प्रमाणपत्र" : "Certification", value: profile.certification }, { icon: Wrench, label: hi ? "अनुभव" : "Experience", value: profile.experienceLabel }, { icon: BriefcaseBusiness, label: hi ? "उपलब्धता" : "Availability", value: profile.availability }].map((item) => { const Icon = item.icon; return <div key={item.label} className="bg-white p-5"><span className="flex items-center gap-2 text-xs font-black uppercase tracking-[.08em] text-[#6d8078]"><Icon className="size-4 text-[#196b4f]" />{item.label}</span><p className="mt-2 text-sm font-extrabold leading-6 text-[#304d43]">{item.value}</p></div>; })}</div></section>

      <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
        <div className="space-y-5"><section className="rounded-[26px] border border-[#d9e2da] bg-white p-5 sm:p-6"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-[family-name:var(--font-display)] text-2xl font-bold"><BriefcaseBusiness className="size-5 text-[#196b4f]" />{hi ? "ऊपर के पात्र अवसर" : "Top eligible opportunities"}</h2><span className="rounded-full bg-[#e4f2dd] px-3 py-1 text-xs font-black text-[#3d7736]">{eligible.length} eligible</span></div><div className="space-y-3">{eligible.map((match) => <div key={match.opportunity.id} className="rounded-2xl border border-[#e0e6e1] bg-[#fafbf9] p-4"><div className="flex items-start justify-between gap-3"><div><strong className="block text-sm text-[#28483d]">{match.opportunity.title}</strong><span className="mt-1 block text-xs text-[#71817b]">{match.opportunity.organisation} · {match.opportunity.location}</span></div><span className="rounded-lg bg-[#196b4f] px-2.5 py-1.5 text-xs font-black text-white">{match.relevanceScore}%</span></div><div className="mt-3"><SourceCitation name={match.opportunity.sourceName} rowId={match.opportunity.sourceRowId} /></div></div>)}</div></section><section className="rounded-[26px] border border-[#d9e2da] bg-white p-5 sm:p-6"><h2 className="flex items-center gap-2 font-[family-name:var(--font-display)] text-2xl font-bold"><Wrench className="size-5 text-[#196b4f]" />{hi ? "पहचाने गए हुनर" : "Skills with evidence"}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{profile.skills.map((skill) => <div key={skill.name} className="rounded-xl bg-[#f3f7f3] p-3"><div className="flex items-center justify-between"><strong className="text-sm text-[#315047]">{skill.name}</strong><span className="text-xs font-black text-[#4d7868]">{skill.confidence}%</span></div><p className="mt-2 text-xs leading-5 text-[#718079]">{skill.evidence}</p></div>)}</div></section></div>

        <div className="space-y-5"><section className="rounded-[26px] border border-[#ead8af] bg-[#fff9e9] p-5 sm:p-6"><h2 className="flex items-center gap-2 font-[family-name:var(--font-display)] text-2xl font-bold text-[#584924]"><ClipboardCheck className="size-5" />{hi ? "मुख्य qualification gaps" : "Qualification gaps"}</h2><div className="mt-4 space-y-3">{near.map((match) => <div key={match.opportunity.id} className="rounded-2xl bg-white p-4"><strong className="text-sm text-[#51462d]">{match.opportunity.title}</strong>{match.missing.map((item) => <p key={item.id} className="mt-2 text-xs leading-5 text-[#78683f]">Missing: {item.simple}</p>)}</div>)}</div></section><section className="rounded-[26px] border border-[#d7e2da] bg-white p-5 sm:p-6"><h2 className="flex items-center gap-2 font-[family-name:var(--font-display)] text-2xl font-bold"><BookOpenCheck className="size-5 text-[#196b4f]" />{hi ? "सुझाए गए course" : "Suggested courses"}</h2><div className="mt-4 space-y-3">{relevantCourses.map((course) => <div key={course.id} className="rounded-2xl bg-[#f4f7f3] p-4"><strong className="text-sm text-[#2c4b40]">{course.title}</strong><p className="mt-1 text-xs text-[#708079]">{course.provider} · {course.duration}</p><p className="mt-2 text-xs leading-5 text-[#526960]">May help: {course.closesGap}</p><div className="mt-2"><SourceCitation name={course.sourceName} rowId={course.sourceRowId} /></div></div>)}</div><p className="mt-3 text-[11px] text-[#806d44]">Courses may help close a gap; they do not promise employment.</p></section><section className="rounded-[26px] border border-[#bfd6c4] bg-[#eef7ef] p-5"><h3 className="flex items-center gap-2 font-black text-[#315a3c]"><Check className="size-5" />{hi ? "रिज़्यूमे स्थिति: तैयार" : "Resume status: Ready"}</h3><p className="mt-2 text-sm leading-6 text-[#60736a]">{hi ? "Candidate-reviewed bilingual one-page resume." : "Candidate-reviewed bilingual one-page resume."}</p></section></div>
      </div>
    </div>
  );
}
