"use client";

import { useState } from "react";
import { ArrowLeft, Check, ChevronDown, Copy, Lightbulb, Mic, RotateCcw, Sparkles, Square, Target } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { AppLanguage, CandidateProfile, OpportunityMatch } from "@/lib/product-types";

export function InterviewScreen({ language, profile, match, onBack, onComplete }: { language: AppLanguage; profile: CandidateProfile; match: OpportunityMatch; onBack: () => void; onComplete: () => void }) {
  const hi = language === "hi";
  const [open, setOpen] = useState<string | null>(match.opportunity.interviewQuestions[0]?.id ?? null);
  const [practising, setPractising] = useState<string | null>(null);
  const [feedback, setFeedback] = useState<string | null>(null);
  const [copied, setCopied] = useState<string | null>(null);
  const questions = match.opportunity.interviewQuestions;

  const copyAnswer = async (id: string, text: string) => {
    try { await navigator.clipboard.writeText(text); setCopied(id); window.setTimeout(() => setCopied(null), 1200); } catch { /* clipboard not available */ }
  };

  const togglePractice = (id: string) => {
    if (practising === id) { setPractising(null); setFeedback(id); }
    else { setPractising(id); setFeedback(null); }
  };

  return (
    <div className="mx-auto w-full max-w-[1320px] px-4 pb-28 pt-7 sm:px-7 lg:px-12 lg:pt-9">
      <button onClick={onBack} className="mb-5 inline-flex min-h-10 items-center gap-2 rounded-xl pr-3 text-sm font-extrabold text-[#557067] hover:bg-[#e9f1ea]"><ArrowLeft className="size-4" />{hi ? "अवसर पर वापस" : "Back to opportunity"}</button>
      <section className="relative overflow-hidden rounded-[30px] bg-[#173f34] p-6 text-white shadow-[0_24px_70px_#1c3c3118] sm:p-9"><div className="absolute -right-12 -top-24 size-72 rounded-full border-[45px] border-white/5" /><div className="relative grid gap-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-xs font-black"><Target className="size-4 text-[#dff0a7]" />{hi ? "आपकी role-specific तैयारी" : "Your role-specific practice"}</span><h1 className="mt-5 font-[family-name:var(--font-display)] text-4xl font-bold tracking-[-.04em] sm:text-5xl">{hi ? `${match.opportunity.titleHi} की तैयारी` : `Let’s prepare for ${match.opportunity.title}`}</h1><p className="mt-3 max-w-2xl text-[15px] leading-7 text-white/70">{hi ? `${profile.name} की profile और listing की शर्तों से तैयार 5 संभावित सवाल। जवाब सरल और candidate level के अनुसार हैं।` : `Five likely questions based on ${profile.name}’s profile and this listing. Answers are simple, honest and right for a first interview.`}</p></div><div className="rounded-2xl bg-[#dff0a7] p-4 text-[#2f5023]"><span className="block text-3xl font-black">5</span><span className="text-xs font-black">{hi ? "मुख्य सवाल" : "key questions"}</span></div></div></section>

      <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(310px,.65fr)]">
        <main className="space-y-3">{questions.map((question, index) => { const isOpen = open === question.id; const answer = hi ? question.answerHi : question.answer; return <article key={question.id} className="overflow-hidden rounded-[22px] border border-[#d9e2da] bg-white shadow-[0_10px_35px_#203e3408]"><button onClick={() => setOpen(isOpen ? null : question.id)} className="flex w-full items-start gap-4 p-5 text-left"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#e8f1ea] text-sm font-black text-[#196b4f]">{index + 1}</span><span className="flex-1"><span className="block font-black leading-6 text-[#28483d]">{hi ? question.questionHi : question.question}</span><small className="mt-1 block text-xs text-[#7a8983]">{hi ? "लगभग 45 सेकंड · आसान" : "About 45 sec · Easy"}</small></span><ChevronDown className={`mt-1 size-5 text-[#73827c] transition ${isOpen ? "rotate-180" : ""}`} /></button>{isOpen && <div className="border-t border-[#e1e7e1] p-5"><div className="rounded-2xl border border-[#cfe1d2] bg-[#eef6ef] p-4"><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.09em] text-[#477256]"><Sparkles className="size-4" />{hi ? "सुझाया जवाब" : "Suggested answer"}</p><p className="mt-3 text-[15px] leading-7 text-[#365349]">{answer}</p><div className="mt-4 flex flex-wrap gap-2"><Button onClick={() => copyAnswer(question.id, answer)} variant="outline" className="min-h-10 rounded-xl border-[#bfd2c3] bg-white text-[#315648]"><Copy />{copied === question.id ? (hi ? "कॉपी हुआ" : "Copied") : (hi ? "जवाब कॉपी करें" : "Copy answer")}</Button><Button onClick={() => togglePractice(question.id)} className={`min-h-10 rounded-xl font-black ${practising === question.id ? "bg-[#c24f40] hover:bg-[#ac4337]" : "bg-[#196b4f]"}`}>{practising === question.id ? <Square fill="currentColor" /> : <Mic />}{practising === question.id ? (hi ? "जवाब रोकें" : "Stop answer") : (hi ? "आवाज़ में अभ्यास" : "Practise by voice")}</Button></div></div><div className="mt-3 flex items-start gap-2 rounded-xl bg-[#fff8e6] p-3 text-xs leading-5 text-[#705e33]"><Lightbulb className="mt-0.5 size-4 shrink-0" /><span><strong>{hi ? "याद रखें:" : "Remember:"}</strong> {question.tip}</span></div>{feedback === question.id && <div className="mt-3 rounded-2xl border border-[#d5e2d7] bg-white p-4"><p className="flex items-center gap-2 font-black text-[#2f5a41]"><Check className="size-5 text-[#4f9247]" />{hi ? "अच्छी शुरुआत" : "Strong start"}</p><p className="mt-2 text-sm leading-6 text-[#687a72]">{hi ? "आपका जवाब स्पष्ट था। बेहतर बनाने के लिए safety step पहले बोलें और एक छोटा practical example जोड़ें।" : "Your answer was clear. Improve it by naming the safety step first and adding one short practical example."}</p><Button onClick={() => setFeedback(null)} variant="ghost" className="mt-2 h-9 rounded-lg text-[#196b4f]"><RotateCcw />{hi ? "फिर से कोशिश" : "Try again"}</Button></div>}</div>}</article>; })}</main>

        <aside className="space-y-4 lg:sticky lg:top-24 lg:self-start"><section className="rounded-[24px] border border-[#d9e2da] bg-white p-5"><h2 className="font-black">{hi ? "आपकी तैयारी" : "Your preparation"}</h2><div className="mt-5 space-y-4">{[{ label: hi ? "सवाल देखे" : "Questions reviewed", value: Math.max(1, open ? 2 : 1), total: 5 }, { label: hi ? "आवाज़ में अभ्यास" : "Voice practices", value: feedback ? 1 : 0, total: 5 }].map((item) => <div key={item.label}><div className="flex justify-between text-xs font-bold text-[#5c7268]"><span>{item.label}</span><span>{item.value}/{item.total}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#e7ece8]"><div className="h-full rounded-full bg-[#196b4f] transition-all" style={{ width: `${(item.value / item.total) * 100}%` }} /></div></div>)}</div></section><section className="rounded-[24px] border border-[#ead7aa] bg-[#fff8e5] p-5"><h3 className="font-black text-[#604d25]">{hi ? "इंटरव्यू में 3 बातें" : "Three interview habits"}</h3><ul className="mt-3 space-y-3 text-sm leading-6 text-[#72623e]"><li className="flex gap-2"><Check className="mt-1 size-4 shrink-0 text-[#64863f]" />{hi ? "धीरे और अपनी भाषा में साफ़ बोलें" : "Speak slowly and clearly in your own language"}</li><li className="flex gap-2"><Check className="mt-1 size-4 shrink-0 text-[#64863f]" />{hi ? "अनौपचारिक अनुभव को ईमानदारी से बताएँ" : "Be honest about informal experience"}</li><li className="flex gap-2"><Check className="mt-1 size-4 shrink-0 text-[#64863f]" />{hi ? "सुरक्षा को हर technical answer में पहले रखें" : "Put safety first in technical answers"}</li></ul></section><Button onClick={onComplete} className="min-h-12 w-full rounded-xl bg-[#196b4f] font-black"><Check />{hi ? "तैयारी पूरी करें" : "Finish preparation"}</Button></aside>
      </div>
    </div>
  );
}
