"use client";

import { ArrowLeft, ArrowRight, BookOpenCheck, BriefcaseBusiness, CalendarDays, Check, CircleAlert, GraduationCap, IndianRupee, MapPin, ShieldCheck, Wrench, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { courses } from "@/data/opportunities";
import type { AppLanguage, CandidateProfile, OpportunityMatch } from "@/lib/product-types";
import { SourceCitation, StatusIcon } from "@/components/bhasha/shared";
import { OpportunityVisual } from "@/components/bhasha/opportunity-visual";

export function OpportunityDetailScreen({ language, profile, match, onBack, onPrepare, onResume }: { language: AppLanguage; profile: CandidateProfile; match: OpportunityMatch; onBack: () => void; onPrepare: () => void; onResume: () => void }) {
  const hi = language === "hi";
  const { opportunity } = match;
  const relatedCourses = courses.filter((course) => course.relatedTrades.includes(profile.trade ?? "")).slice(0, 2);
  return (
    <div className="mx-auto w-full max-w-[1240px] px-4 pb-28 pt-7 sm:px-7 lg:px-12 lg:pt-9">
      <button onClick={onBack} className="mb-5 inline-flex min-h-10 items-center gap-2 rounded-xl pr-3 text-sm font-extrabold text-[#557067] hover:bg-[#e9f1ea]"><ArrowLeft className="size-4" />{hi ? "सभी अवसर" : "All opportunities"}</button>
      <div className="grid gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(310px,.65fr)]">
        <main className="space-y-5">
          <section className="overflow-hidden rounded-[28px] border border-[#d8e2d9] bg-white shadow-[0_20px_60px_#29483d0d]">
            <div className="relative overflow-hidden bg-[#173f34] p-6 text-white sm:p-8"><div className="absolute -right-12 -top-20 size-64 rounded-full border-[44px] border-white/5" /><div className="relative grid gap-6 md:grid-cols-[minmax(0,1fr)_240px]"><div><div className="flex flex-col gap-5 sm:flex-row sm:items-start"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-[#dff0a7] text-[#355626]"><BriefcaseBusiness className="size-6" /></span><div className="flex-1"><span className="text-xs font-bold text-white/65">{opportunity.organisation}</span><h1 className="mt-2 font-[family-name:var(--font-display)] text-3xl font-bold tracking-tight sm:text-4xl">{hi ? opportunity.titleHi : opportunity.title}</h1><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold text-white/75"><span className="flex items-center gap-1.5 rounded-lg bg-white/10 px-2.5 py-1.5"><MapPin className="size-3.5" />{opportunity.location}</span><span className="flex items-center gap-1.5 rounded-lg bg-white/10 px-2.5 py-1.5"><GraduationCap className="size-3.5" />{opportunity.type}</span><span className="flex items-center gap-1.5 rounded-lg bg-white/10 px-2.5 py-1.5"><IndianRupee className="size-3.5" />{opportunity.compensation}</span></div></div><div className={`w-fit rounded-2xl p-4 text-center ${match.eligible ? "bg-[#dff0a7] text-[#315023]" : "bg-[#ffdca1] text-[#684a13]"}`}><span className="block text-2xl font-black">{match.relevanceScore}%</span><span className="text-xs font-black">{hi ? "प्रोफ़ाइल मिलान" : "profile match"}</span></div></div><p className="mt-6 max-w-3xl text-sm leading-7 text-white/72">{opportunity.summary}</p></div><OpportunityVisual opportunity={opportunity} hi={hi} className="aspect-[16/10] rounded-2xl ring-1 ring-white/15 md:aspect-auto md:min-h-[210px]" sizes="(max-width: 768px) 100vw, 240px" priority /></div></div>
            <div className="flex flex-wrap items-center justify-between gap-3 p-5 sm:p-6"><SourceCitation name={opportunity.sourceName} rowId={opportunity.sourceRowId} /><span className="flex items-center gap-1.5 text-xs text-[#7b8984]"><CalendarDays className="size-4" />{opportunity.posted}</span></div>
          </section>

          <section className="rounded-[28px] border border-[#d8e2d9] bg-white p-5 sm:p-7"><div className="mb-6"><p className="text-xs font-black uppercase tracking-[.11em] text-[#5c8173]">{hi ? "हर शर्त आसान भाषा में" : "Every requirement, explained"}</p><h2 className="mt-1 font-[family-name:var(--font-display)] text-3xl font-bold tracking-tight">{hi ? "पात्रता की पूरी जाँच" : "Complete eligibility check"}</h2></div><div className="space-y-3">{match.requirements.map((requirement, index) => { const RequirementIcon = { education: GraduationCap, certification: ShieldCheck, experience: BriefcaseBusiness, location: MapPin, skill: Wrench }[requirement.type]; return <article key={requirement.id} className="rounded-2xl border border-[#dfe6e0] bg-[#fbfcfa] p-4 sm:p-5"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#eaf2eb] text-[#196b4f]"><RequirementIcon className="size-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[11px] font-black uppercase tracking-[.09em] text-[#71827a]">{hi ? `शर्त ${index + 1}` : `Requirement ${index + 1}`}</p><h3 className="mt-1 text-[15px] font-black leading-6 text-[#2c4b40]">{hi ? requirement.simpleHi : requirement.simple}</h3></div><span className={`inline-flex w-fit items-center gap-2 rounded-full px-2.5 py-1 text-[11px] font-black ${requirement.status === "met" ? "bg-[#e4f3dd] text-[#397634]" : requirement.status === "missing" ? "bg-[#fde8e4] text-[#a23f36]" : "bg-[#fff1cc] text-[#82621b]"}`}><StatusIcon status={requirement.status} />{requirement.status === "met" ? (hi ? "आपके पास है" : "You have this") : requirement.status === "missing" ? (hi ? "अभी कम है" : "Still missing") : (hi ? "जानकारी चाहिए" : "Need more info")}</span></div><p className="mt-3 rounded-xl bg-[#eef6ef] px-3 py-2.5 text-xs leading-5 text-[#536b61]"><strong className="text-[#365648]">{hi ? "आपकी प्रोफ़ाइल:" : "Your profile:"}</strong> {requirement.reason}</p><details className="mt-2 text-xs text-[#6e7d77]"><summary className="cursor-pointer font-bold text-[#597168]">{hi ? "Listing की औपचारिक शर्त देखें" : "See formal listing wording"}</summary><p className="mt-2 border-l-2 border-[#d7e1d9] pl-3 leading-5">“{requirement.formal}”</p></details></div></div></article>; })}</div></section>
        </main>

        <aside className="space-y-5 lg:sticky lg:top-24 lg:self-start">
          <section className={`rounded-[26px] border p-5 ${match.eligible ? "border-[#b9d6bf] bg-[#edf7ef]" : "border-[#ebc8bc] bg-[#fff0ed]"}`}><span className={`grid size-12 place-items-center rounded-2xl ${match.eligible ? "bg-[#196b4f] text-white" : "bg-[#c24f40] text-white"}`}>{match.eligible ? <Check className="size-6" strokeWidth={3} /> : <X className="size-6" strokeWidth={3} />}</span><p className="mt-4 text-xs font-black uppercase tracking-[.1em] text-[#60766d]">{hi ? "आपकी पात्रता" : "Your eligibility"}</p><h2 className={`mt-1 text-2xl font-black ${match.eligible ? "text-[#285a34]" : "text-[#913b33]"}`}>{match.eligible ? (hi ? "आप पात्र हैं" : "ELIGIBLE") : (hi ? "अभी पात्र नहीं" : "NOT CURRENTLY ELIGIBLE")}</h2><p className="mt-3 text-sm leading-6 text-[#5f7169]">{match.eligible ? (hi ? "आप इस snapshot में दी गई सभी ज़रूरी शर्तें पूरी करते हैं। अगला कदम तैयारी करना है।" : "You meet every hard requirement in this snapshot. Your next step is to prepare.") : (hi ? `${match.missing.length} ज़रूरी शर्त अभी पूरी नहीं होती। नीचे साफ़ next step दिया गया है।` : `${match.missing.length} hard requirement is not met yet. There is a clear next step below.`)}</p><Button onClick={match.eligible ? onPrepare : onResume} className="mt-5 min-h-12 w-full rounded-xl bg-[#196b4f] font-black">{match.eligible ? (hi ? "इस role की तैयारी करें" : "Prepare for this role") : (hi ? "पहले रिज़्यूमे तैयार करें" : "Build my resume")}<ArrowRight /></Button><p className="mt-3 flex items-start gap-2 text-[11px] leading-5 text-[#718179]"><ShieldCheck className="mt-0.5 size-3.5 shrink-0" />{hi ? "हम केवल जानकारी और तैयारी देते हैं। आवेदन आप स्वयं तय करेंगे।" : "We provide information and preparation. You decide whether to apply."}</p></section>

          {!match.eligible && (
            <section className="rounded-[26px] border border-[#e6d7b5] bg-[#fff9ea] p-5">
              <h3 className="flex items-center gap-2 font-black text-[#5b4a25]"><CircleAlert className="size-5" />{hi ? "कमी कैसे पूरी हो सकती है?" : "How could you close the gap?"}</h3>
              <div className="mt-4 space-y-2">
                {match.missing.length > 0 && match.missing.map((item) => <div key={item.id} className="rounded-xl bg-white p-3 text-sm leading-6 text-[#675837]"><strong className="block text-[#443b25]">{hi ? "कम है:" : "Missing:"}</strong>{hi ? item.simpleHi : item.simple}</div>)}
                {match.needsInfo.length > 0 && match.needsInfo.map((item) => <div key={item.id} className="rounded-xl border border-[#f0dcb4] bg-[#fffaf1] p-3 text-sm leading-6 text-[#6b5326]"><strong className="block text-[#4d3e1f]">{hi ? "सत्यापन ज़रूरी:" : "Needs verification:"}</strong>{hi ? item.simpleHi : item.simple}</div>)}
              </div>
            </section>
          )}

          <section className="rounded-[26px] border border-[#d9e2da] bg-white p-5"><h3 className="flex items-center gap-2 font-black"><BookOpenCheck className="size-5 text-[#196b4f]" />{hi ? "मददगार स्थानीय कोर्स" : "Helpful local courses"}</h3><div className="mt-4 space-y-3">{relatedCourses.map((course) => <div key={course.id} className="rounded-xl bg-[#f4f7f3] p-3"><strong className="block text-sm text-[#2e4c41]">{hi ? course.titleHi : course.title}</strong><span className="mt-1 block text-xs text-[#708079]">{course.provider} · {course.duration}</span><p className="mt-2 text-xs leading-5 text-[#536b61]">{hi ? "यह योग्यता की कमी पूरी करने में मदद कर सकता है।" : "This may help close the qualification gap."}</p><div className="mt-2"><SourceCitation name={course.sourceName} rowId={course.sourceRowId} /></div></div>)}</div><p className="mt-3 text-[11px] text-[#826f45]">{hi ? "Course करने से नौकरी की गारंटी नहीं मिलती।" : "Completing a course does not guarantee employment."}</p></section>
        </aside>
      </div>
    </div>
  );
}
